name: Flat
on:
  push:
    paths:
      - .github/workflows/flat.yml
      - postprocess.js
  workflow_dispatch: null
  schedule:
    - cron: "*/30 * * * *"
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.bittrex.com/api/v1.1/public/getmarketsummaries
          downloaded_filename: flat/bittrex_marketsummaries.json
          postprocess: postprocess.js
        env:
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./flat
